name: car_note
description: A special app for your car.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  intl: ^0.18.1
  font_awesome_flutter: ^10.6.0
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  awesome_notifications: ^0.8.2
  get_it: ^7.6.4
  bot_toast: ^4.1.3
  dartz: ^0.10.1
  document_file_save_plus: ^2.0.0
  cron: ^0.5.1
  flutter_staggered_animations: ^1.1.1
  tutorial_coach_mark: ^1.2.11
  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.1.0
#  google_mobile_ads: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

#dependency_overrides:
#  # Remove when awesome_notifications stops relying on 0.17.0.
#  # https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_localizations/pubspec.yaml#L18
#  intl: ^0.17.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  #  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - lang/ar.json
    - lang/en.json
    - assets/images/
    - assets/images/dashboard_lights/
    - assets/images/dashboard_lights/warning/
    - assets/images/dashboard_lights/advisory/
    - assets/images/dashboard_lights/info/
    - assets/images/onboarding/

  fonts:
    - family: ArabicTwo
      fonts:
        - asset: assets/fonts/ArabicTwo.ttf
        - asset: assets/fonts/ArabicTwo Bold.ttf
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Bold.ttf
        - asset: assets/fonts/Product Sans Bold Italic.ttf
        - asset: assets/fonts/Product Sans Italic.ttf
        - asset: assets/fonts/Product Sans Regular.ttf
          style: italic
    - family: DIN Next
      fonts:
        - asset: assets/fonts/DIN Next Rounded LT W01 Regular.ttf